# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

version: "3.9"
services:
  os2mo-graphql-subscriptions:
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0"]
    environment:
      AMQP_URL: "amqp://guest:guest@msg_broker:5672/"
    networks:
      - os2mo_default
    ports:
      - "8000:8000"
    volumes:
      - ./os2mo_graphql_subscriptions:/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://os2mo-graphql-subscriptions:8000/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  os2mo_default:
    external: true
